#!/bin/bash
export TERM=xterm
touch /root/.system
echo "──────────────────────────"
echo "            SSH/Dropbear User Login"
echo "──────────────────────────"
echo "    USERNAME      TOTAL"

mulog=$(cekssh)
data=( $(cat /etc/passwd | grep home | cut -d ' ' -f 1 | cut -d : -f 1) )

for user in "${data[@]}"
do
    cekcek=$(echo "$mulog" | grep "$user" | wc -l)
    if [[ $cekcek -gt 0 ]]; then
        limit_file="/etc/kyt/limit/ssh/ip/$user"

        # Cek apakah file limit ada, jika tidak buat otomatis dengan isi default "1"
        if [[ ! -f "$limit_file" ]]; then
            echo "1" > "$limit_file"
        fi

        iplimit=$(cat "$limit_file")
        printf "  %-13s %-7s %-8s %2s\n" "     $user         $cekcek PID"
        echo "slot" >> /root/.system
    fi
    sleep 0.1
done

echo -e ""
echo -e "──────────────────────────"
echo -e "     Terimakasih sudah menggunakan-"
echo -e "        Script Credit by Agung"
echo -e "──────────────────────────"
echo -e ""
